# Generated by Django 4.1.1 on 2023-04-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pins', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(blank=True, null=True)),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pins.pins')),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pins.profile')),
            ],
        ),
    ]
